name: injuredpixels
description: A utility app for detecting dead, stuck, or hot pixels on LCD/OLED displays.
version: 5.0.0
repository: https://github.com/aurelitec/injuredpixels

environment:
  sdk: ^3.10.8

dependencies:
  signals_core: ^6.2.1
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.10.5
  build_web_compilers: ^4.4.9
  lints: ^6.1.0
