name: injuredpixels
description: A utility app for detecting dead, stuck, or hot pixels on LCD/OLED displays.
version: 5.0.0
repository: https://github.com/aurelitec/injuredpixels

environment:
  sdk: ^3.11.0

dependencies:
  web: ^1.1.1

dev_dependencies:
  build_runner: ^2.11.1
  build_web_compilers: ^4.4.11
  lints: ^6.1.0
